### ISSUE TITLE
Kerberos support for Python3

### ISSUE THREAD

**Issue by elukey** [internetarchive/snakebite-py3#5]
Hi!

I found this fork while looking at Apache Airflow's support for HDFS, and I am wondering if I can help in updating the code base (if nobody is already looking into it). I work for the Wikimedia foundation and we'd be really interested in using snakebite in production, but we'd need Kerberos support. Is there any work in progress or previous attempts failed that I should be aware of?

Thanks in advance!

**Comment by nlevitt** [comment]
Hmm, the original readme at https://github.com/spotify/snakebite mentions kerberos. I deleted it from our readme in this commit: https://github.com/internetarchive/snakebite-py3/commit/cb3274e2ba47 but I don't remember exactly why. Maybe those kerberos dependencies are only py2? Anyway I would say please go ahead and work on it! Maybe the existing code can be adapted for py3.

**Comment by elukey** [comment]
Reporting my findings:

* the kerberos module seems to be really simple, namely `python-krbV` seems to be used only to get the principal from the credentials cache (if any). I haven't find a simple library that does the same job yet but it shouldn't be that difficult (last famous words!).
* While testing some changes, I found https://github.com/spotify/snakebite/pull/153#issuecomment-121290538 - it seems that snakebite doesn't support kerberos+RPC-encryption. It would be great to add support for it as well, I see rcp encryption as natural step when kerberos is enabled but people might have different opinions.

**Comment by elukey** [comment]
@nlevitt I think that with the above pull request, snakebite should work fine with Kerberos clients. The only thing missing is making it work with encrypted RPCs, still working on it.

I tested the library on my CDH5 (Kerberized) cluster and it seems working well, feedback welcome :)

**Comment by elukey** [comment]
@nlevitt I was able to make snakebite work with encrypted comms between client and Namenode, I'll send a pull request when the code is tidy enough. I'll then need to make client to datanode encrypted comms to work, but for the moment things like stat/ls/etc.. work fine (basically the ones that only need to communicate with the Namenode).

I am seeing little traction on this issue so I am wondering what you think about adding/maintaining code for snakebite in the long term. I'd be willing to help in maintaining it, and also to contribute with more code. It seems worth to maintain a pure python hdfs client implementation (especially in light of things like Apache Airflow) but not sure what the Internet Archive's plans are.

**Comment by nlevitt** [comment]
Our level of engagement with this project is basically as described in the readme. "We maintain it enough to work for our needs at the Internet Archive.... Please help us improve this!" I'm glad that others are using and contributing to it and would like to make that as easy as possible. To that end, I have added you as a contributor with write privileges, @elukey. I'll do the same for anyone else who submits a good pull request and is interested.

**Comment by nlevitt** [comment]
Resolved by #6, thanks @elukey!

**Comment by elukey** [comment]
Thank you! Looking forward to collaborate more :)
